# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20180501_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettokens',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
