# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_auto_20180501_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
    ]
